### ISSUE TITLE
When using store of a single item don't require wrapping it in a list

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#113]
currently you have to do this
metob.store( [item] )

this often throws me off and I think when its just a single thing, the list wrapping should happen without the user knowing.

metob.store( item ) should work.

**Comment by blink1073** [comment]
Hmm, this *should* work: https://github.com/metabolite-atlas/metatlas/blob/master/metatlas/object_helpers.py#L185

**Comment by benbowen** [comment]
You're right.  It does work.  I have to work harder to reproduce whatever I was doing.
