### ISSUE TITLE
Need base peak chromatogram

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#12]
Maybe using a binned statistic

**Comment by blink1073** [comment]
http://docs.scipy.org/doc/scipy-dev/reference/generated/scipy.stats.binned_statistic.html

**Comment by blink1073** [comment]
Chromatogram obtained by plotting the signal of the ions represented by the base peak detected in each of a series of mass spectra recorded as a function of retention time.

http://mass-spec.lsu.edu/msterms/index.php/Base_peak_chromatogram

**Comment by blink1073** [comment]
Todo: test get_Chromatagram against get_XIC in terms of time and validity.
