### ISSUE TITLE
Database & Filesystem Integrity monitor

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#19]
We need to routinely ensure that the LcmsRuns all point to actual runs.  Currently given the way permissions are handled, a user could move a file and the database wouldn't know a file was deleted.

**Comment by blink1073** [comment]
Script to run once per day:
Look for entries in the database where the file is not there
Email the person with the list of files missing
Offer a command to prune unreachable runs for a given user
This command is `remove_objects(find_invalid_runs)`

Needs a new object model:
We have the object id, the version id, and the prev object id that way, we can group things by object id
Then, if you remove an object, you can do so by object id.
Also, provenance gets a bit cleaner.

**Comment by blink1073** [comment]
Will need to update the primary key in the db to `version_id`

**Comment by blink1073** [comment]
Notes to self:  added a group_id as a new parameter, requiring no destructive changes to current table.
This allows us to query and get only the newest object by group_id, as well as remove all objects matching a group_id.
Todo: 
- [ ] test the semantics of group_id
- [ ] add group_id to existing entries in the database
- [ ] finish remove_objects
- [ ] add the cron job outlined above

**Comment by blink1073** [comment]
Fixed by 0f14ef3.

**Comment by blink1073** [comment]
Need to use actual owner of file.

**Comment by blink1073** [comment]
`pwd.getpwuid(os.stat(fname).st_uid).pw_name`

**Comment by blink1073** [comment]
Fully finished: https://github.com/metabolite-atlas/metatlas/blob/bfb284c894670ce1cca11e613d0ea6a01a10a11a/metatlas/directory_watcher.py
