### ISSUE TITLE
Need a way to remove metatlas objects

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#24]
I accidentally moved a large amount of mislabeled files into "raw_data".  We need best practices for how to deal with this.  IMO, the files should be deleted and the database entries should be removed.  I'm not sure how to do this.

**Comment by blink1073** [comment]
Please remove the files, so they are not picked up when I regenerate the LCMSRuns.  Once I finish #19, this will be taken care of.

In general, do you want an API to remove objects, something like `metob.remove(list_of_objects)`?

**Comment by benbowen** [comment]
Files are removed.  

I think your spec makes sense for the API, but I think it should require special authorization privileges.  Can be added when user model is built up.

**Comment by blink1073** [comment]
Fixed in a61d5d1.  If you call `remove`, it will default to just your own objects, and will still ask for confirmation before removing.
