### ISSUE TITLE
Add two fields to "Compound" table

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#25]
A little oversight... Please add "Formula" and "MonoIsotopic_Molecular_Weight" to the compounds table.  Formula will be a string (like C6H6O6).  Monoisotopic_Molecular_Weight will be a float.

**Comment by benbowen** [comment]
Also add field "Synonyms" as a string

**Comment by benbowen** [comment]
Also add "url" as string to the Reference_Databases table

**Comment by blink1073** [comment]
Closed in 08c8b87.
