### ISSUE TITLE
See if I'm bulk loading compounds correctly

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#26]
I'm currently doing it like this from a spreadsheet with ~10K compounds in it.  Is there another easy way?
![screen shot 2015-10-02 at 4 27 11 pm](https://cloud.githubusercontent.com/assets/810953/10259888/942be0a6-6922-11e5-9e51-90eced495e77.png)

**Comment by blink1073** [comment]
I am going to add a `storeObjects` function that will take a list of objects and intelligently group the queries to the database, and do the same with `queryDatabase`, that should make this much cleaner.

**Comment by blink1073** [comment]
Here's what you'd do after I merge #29, clear the database, and load all the `LCMSRun`s:

```
compounds = []
for myCompound in metacyc_compounds:
    c = metob.Compound()
    c.InChI = myCompound['InChI']
    c.name = myCompound['Common-Name']
    compounds.append(c)
metob.store(compounds)
```

**Comment by benbowen** [comment]
If you are planning to nuke the database today let me know, and afterwards I'll try "store" for new metatlas compounds

**Comment by benbowen** [comment]
nevermind
done

**Comment by blink1073** [comment]
I just nuked the database.

**Comment by blink1073** [comment]
I'll go back in after lunch and add the LCMSRuns.

**Comment by benbowen** [comment]
looks good
![image](https://cloud.githubusercontent.com/assets/810953/10373166/91f29316-6da0-11e5-8e0a-d1bc977935c1.png)

**Comment by blink1073** [comment]
sweetness

**Comment by benbowen** [comment]
Much faster! "retrieve" fails because a table "functional_sets" hasn't been
created yet.

**Comment by blink1073** [comment]
Noted, creating issue.

**Comment by blink1073** [comment]
%%time
store(runs)
CPU times: user 4.86 s, sys: 67 ms, total: 4.93 s
Wall time: 5.51 s
In [11]:

%%time
a = retrieve('lcmsrun')
CPU times: user 5.19 s, sys: 127 ms, total: 5.32 s
Wall time: 5.4 s
In [12]:

len(a)
Out[12]:
7296

Done.
