### ISSUE TITLE
Speed up queries that return large numbers of objects

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#27]
If the scripts I ran this afternoon worked, there are ~10K compounds in the databse now.

allCompounds = metob.queryDatabase('Compound')
print len(allCompounds)

Takes forever (hasn't finished yet). Is there a way to speed it up?

**Comment by blink1073** [comment]
Once #29 is pushed, this will be called as `metob.retrieve("compound")` and will be much faster.
