### ISSUE TITLE
traitlets collision from schema evolution and query

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#34]
I think that some cryptic behavior has emerged as a result of database schema evolution. The old values that had "none" as Monoisotopic_molecular_weight. Break the query database command.  Perhaps this bug is a good place to identify tests and migration tools.

allCompounds = metob.queryDatabase('Compound',name = '%glycine%')
print len(allCompounds)
---------------------------------------------------------------------------
TraitError                                Traceback (most recent call last)
<ipython-input-75-dd5285110118> in <module>()
----> 1 allCompounds = metob.queryDatabase('Compound',name = '%glycine%')
      2 print len(allCompounds)

/global/project/projectdirs/metatlas/anaconda/lib/python2.7/site-packages/metatlas/metatlas_objects.pyc in queryDatabase(object_type, **kwargs)
    224                   if i['unique_id'] not in prev_uuids]
    225     items = [klass(unique_id=i) for i in unique_ids]
--> 226     return [i.retrieve() for i in items]
    227 
    228 

/global/project/projectdirs/metatlas/anaconda/lib/python2.7/site-packages/metatlas/metatlas_objects.pyc in retrieve(self, name)
    313         """
    314         self._loopback_guard = True
--> 315         value = workspace.load(self, name)
    316         self._changed = False
    317         self._loopback_guard = False

/global/project/projectdirs/metatlas/anaconda/lib/python2.7/site-packages/metatlas/metatlas_objects.pyc in load(self, obj, name)
    158             else:
    159                 # set the attribute directly
--> 160                 setattr(obj, tname, entry[tname])
    161         del self.seen[obj.unique_id]
    162         # return object for parent usage

//anaconda/lib/python2.7/site-packages/IPython/utils/traitlets.pyc in __set__(self, obj, value)
    428 
    429     def __set__(self, obj, value):
--> 430         new_value = self._validate(obj, value)
    431         try:
    432             old_value = obj._trait_values[self.name]

//anaconda/lib/python2.7/site-packages/IPython/utils/traitlets.pyc in _validate(self, obj, value)
    449             return value
    450         if hasattr(self, 'validate'):
--> 451             return self.validate(obj, value)
    452         elif hasattr(self, 'is_valid_for'):
    453             valid = self.is_valid_for(value)

//anaconda/lib/python2.7/site-packages/IPython/utils/traitlets.pyc in validate(self, obj, value)
   1200             return float(value)
   1201         except:
-> 1202             self.error(obj, value)
   1203 
   1204 class Complex(TraitType):

//anaconda/lib/python2.7/site-packages/IPython/utils/traitlets.pyc in error(self, obj, value)
    478             e = "The '%s' trait must be %s, but a value of %r was specified." \
    479                 % (self.name, self.info(), repr_type(value))
--> 480         raise TraitError(e)
    481 
    482     def get_metadata(self, key, default=None):

TraitError: The 'MonoIsotopic_molecular_weight' trait of a Compound instance must be a float, but a value of None <type 'NoneType'> was specified.

**Comment by blink1073** [comment]
Fixed in 9dcb9ce.
