### ISSUE TITLE
"retrieve" with "created_by" fails

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#38]
I ran metob.retrieve('lcmsruns',created_by='pandeer') and returned sql error

**Comment by blink1073** [comment]
That is related to #37, but also, `created_by` => `username`.

**Comment by blink1073** [comment]
import metatlas.metatlas_objects as metob
len(metob.retrieve('lcmsruns',username='pandeer'))
Out[16]:
732
