### ISSUE TITLE
can't store list of groups

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#39]
#make the groups in the database and simultaneously populate the runs
all_my_groups = []
for j,u in enumerate(ugroups):
    indices = [i for i, x in enumerate(group_names) if x == u]
    myGroup = metob.Group()
    myGroup.name = u
    myGroup.description = group_description[j]
    file_set = []
    for index in indices:
        file_set.append(myFiles[index])
    myGroup.items = file_set
    all_my_groups.append(myGroup)
# myGroup
metob.store(all_my_groups)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-42-2a426ca502c5> in <module>()
     12     all_my_groups.append(myGroup)
     13 # myGroup
---> 14 metob.store(all_my_groups)

/global/project/projectdirs/metatlas/anaconda/lib/python2.7/site-packages/metatlas/metatlas_objects.pyc in store(objects)
    336 def store(objects):
    337     """Store Metatlas objects in the database.
--> 338 
    339     Parameters
    340     ----------

/global/project/projectdirs/metatlas/anaconda/lib/python2.7/site-packages/metatlas/metatlas_objects.pyc in save_objects(self, objects)
    179         self._inserts = defaultdict(list)
    180         for obj in objects:
--> 181             self.save(obj)
    182         for (table_name, updates) in self._link_updates.items():
    183             with self.db:

/global/project/projectdirs/metatlas/anaconda/lib/python2.7/site-packages/metatlas/metatlas_objects.pyc in save(self, obj)
    221                 # store the item in its own table
    222                 for subvalue in value:
--> 223                     self.save(subvalue)
    224                     link = dict(source_id=obj.unique_id,
    225                                 target_id=subvalue.unique_id,

/global/project/projectdirs/metatlas/anaconda/lib/python2.7/site-packages/metatlas/metatlas_objects.pyc in save(self, obj)
    237                 else:
    238                     state[tname] = value.unique_id
--> 239                     self.save(value)
    240             elif changed:
    241                 value = getattr(obj, tname)

/global/project/projectdirs/metatlas/anaconda/lib/python2.7/site-packages/metatlas/metatlas_objects.pyc in save(self, obj)
    202         name = obj.__class__.__name__.lower() + 's'
    203         self._seen[obj.unique_id] = True
--> 204         changed, prev_uid = obj._update()
    205         state = dict()
    206         for (tname, trait) in obj.traits().items():

AttributeError: 'Stub' object has no attribute '_update'

**Comment by blink1073** [comment]
Fixed.
