### ISSUE TITLE
speed up mzML to HDF5 conversion

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#4]
It is slow because it is looking at each [mz, intensity] value in each scan.  Instead it should make arrays for the following (using fill values) for scan_time, polarity, mz_level, precursor_MZ, precursor_intensity, and collision_energy and write it once to the hdf5 file as arrays instead of values.  Maybe as a 2d array.

**Comment by benbowen** [comment]
this seems slightly useful:
https://www.mail-archive.com/pytables-users@lists.sourceforge.net/msg03206.html

**Comment by benbowen** [comment]
I did a git push with comments in the file converter inline

**Comment by benbowen** [comment]
I'll wait and hear your thoughts, but this seems like might be the winning ticket:

import numpy as np
import tables as tb
ndim = 60000
h5file = tb.openFile('test.h5', mode='w', title="Test Array")
root = h5file.root
x = h5file.createCArray(root,'x',tb.Float64Atom(),shape=(ndim,ndim))
x[:100,:100] = np.random.random(size=(100,100)) # Now put in some data
h5file.close()

**Comment by blink1073** [comment]
What values if any are constant within a file/spectrum?   

- can there be more than one polarity/ms level per file?
- can precursor intensity and friends vary within a spectrum?

**Comment by benbowen** [comment]
Within a file nothing is constant

Within a spectrum, everything else is constant except [mz, intensity]

For example, the machine determines the ms-level, scan-time, polarity, precursor ion parameters and records a spectrum of ~10K [mz, intensity] values.

**Comment by blink1073** [comment]
Interesting, that changes our storage requirements dramatically.  We can have a LUT for for each spectrum based on the other parameters, and just make each spectrum a 2d array node that can be indexed by the other parameters.

**Comment by blink1073** [comment]
And sort the spectra by mz.

**Comment by benbowen** [comment]
awesome.  I tried to play around with pytables this morning, but I'm making
a mess of things and will stop.

--------------
Email: BPBowen@lbl.gov
Google Voice: (510) 214-6683
Mobile: (480) 225-2341
MS 977-221, Lawrence Berkeley Lab
OpenMSI: http://openmsi.nersc.gov

**Comment by benbowen** [comment]
I just did a file conversion and everything is much faster!  I converted a 1.8GB file in less than a minute to a 0.35 GB hdf5 file.  Checked a few values manually and everything seems in order.

**Comment by blink1073** [comment]
Done.
