### ISSUE TITLE
some files are not showing up in database

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#40]
In this folder: things that were added today are converted, but not in database.
%system ls /project/projectdirs/metatlas/raw_data/pandeer/20151006_PA_DI_QCs/*.h5

**Comment by blink1073** [comment]
Yeah, the directory_watcher script had not been updated, and was failing to create entries.  I can’t get in to ipython.nersc at the moment to fix it…

**Comment by blink1073** [comment]
Fixed.
