### ISSUE TITLE
Potentially a typo in path for file converter cron job

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#43]
I see an extra "/"

myFiles = metob.retrieve('lcmsrun',description='%151002_QE_porewater_pos%') 
for f in myFiles:
    print f.hdf5_file

/global/project/projectdirs/metatlas//raw_data/tls/151002_QE_porewater_pos/150930_HILIC_TS_pos_10E_18h.h5

Note the "//" after "raw_data"

**Comment by blink1073** [comment]
Fixed, I updated the CRON job and fixed the existing hdf and mzml paths in the objects.
