### ISSUE TITLE
format of mz and cfloat traitlets

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#45]
For compounds that I add to the metatlas compound table, they monoisotopic_molecular_weight is returned as a 3 decimal float.  I can't see why.  It seems like the traitlets are doing their job it should be a much bigger floating point number.   In any case, we need more.  At least 5 decimal places and preferably more.

3,6-Dihydroxy-4-methylpyridazine C5H6N2O2 126.043 https://pubchem.ncbi.nlm.nih.gov/compound/79826 InChI=1S/C5H6N2O2/c1-3-2-4(8)6-7-5(3)9/h2H,1H3,(H,6,8)(H,7,9)

**Comment by blink1073** [comment]
Making a note to self: it isn't traitlets, we are sending the full value to the `insert_many` call, but the raw result from the query is truncated.  The column type is `float` in the actual DB, and does not have a precision tied to it in the SqlAlchemy ORM.  Local tests show that we can round-trip arbitrary floating point, even after storing a number with low precision.

**Comment by blink1073** [comment]
Fixed by 2806c2e.
