### ISSUE TITLE
Allow a CompoundIdentification to have list of compounds

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#48]
Currently CompoundIdentification can have compound be none, or valid metatlas compound.  To handle ambiguity, users will want to specify a list of potential compounds.

**Comment by blink1073** [comment]
How about another field called `potential_compounds`?

**Comment by benbowen** [comment]
compound = [] or None, means you have a peak, but no idea what it is
compound = [compound_id] means you believe it is exactly that compound
compound = [compound_id, compound_id, compound_id, etc] means you can't
distinguish among the listed compounds

**Comment by blink1073** [comment]
Fixed in 606510a, and updated in database.
