### ISSUE TITLE
Is there an easier way to see the "type" of reference for a compound identification?

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#49]
This is how I'm doing it now:

http://nbviewer.ipython.org/url/portal.nersc.gov/project/openmsi/MetAtlas_004_Retrieve_Atlas.ipynb?flush_cache=true

atlases = metob.retrieve('Atlas',name='QExactive%')
myAtlas = atlases[0]
for cid in myAtlas.compound_identifications:
    myreferences = cid.retrieve()
    for r in myreferences.references:
        temp = r.retrieve()
        if 'mz' in dir(temp):
            print temp.mz
        if 'RTpeak' in dir(temp):
            print temp.RTpeak

**Comment by blink1073** [comment]
Fixed in 93526bb, use `myAtlas.retrieve_stubs()`.

**Comment by blink1073** [comment]
As of bcc4a9e, you can just access the fields directly, and they will be automatically retrieved as needed.
