### ISSUE TITLE
using precursor ion values in h5_query.get_data()

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#5]
This works:
data = h5q.get_data(fid, ms_level, polarity,
                    min_mz=500,
                    max_mz=550,
                    min_rt=9,
                    max_rt=11)

This doesn't:
data = h5q.get_data(fid, ms_level, polarity,
                    min_mz=500,
                    max_mz=550,
                    min_rt=9,
                    max_rt=11,
                    min_precursor_MZ=0,
                    max_precursor_MZ=0)

I thought it was because the get_data def was > & <.  I changed it to >= & <.  Still doesn't work.  Any ideas?

**Comment by benbowen** [comment]
Man... I must be losing my mind today.  Close the comment.  Brain fart.

**Comment by blink1073** [comment]
I added the ability to specify a value.  In your case you'd use:  

```python
data = h5q.get_data(fid, ms_level, polarity,
min_mz=500,
max_mz=550,
min_rt=9,
max_rt=11,
precursor_MZ=0)
```
