### ISSUE TITLE
Scans from this file break the file converter

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#51]
Probably because the file contains empty scans.
/project/projectdirs/metatlas/raw_data/pandeer/20150305_angelo_MSMS/POS_5Dmsms.mzML

I was able to load Pete's files by modifying the file converter on my local machine with a "try" on line 132.  I will not merge this change until I hear from you.  There is probably something cleaner than "try" for this bug.

It affects the Matlab mzXML reader too.

**Comment by blink1073** [comment]
Fixed by acf3bc2.
