### ISSUE TITLE
Filter while searching in a QGrid

### ISSUE THREAD

**Issue by blink1073** [metabolite-atlas/metatlas#58]
When typing in a name, you still have to click the check-boxes to filter by compound name.  It would be nicer if as you were typing in a compound name to the filter, it automatically removed rows.

![image](https://cloud.githubusercontent.com/assets/2096628/11163986/67bc486e-8aa9-11e5-8512-a6cdd3c8d940.png)

**Comment by benbowen** [comment]
This is working
