### ISSUE TITLE
2d hist plots shift around the values

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#6]
Depending on how your mz_edges look, your m/z values will appear in a different place.  I believe this is an artifact of the imshow, but I'm not sure.  In this notebook, for methionine (m/z = 149.051 + 1.007276) you see if bouncing around in the 2d hists depending on the mz_edges.

Example:
http://nbviewer.ipython.org/github/metabolite-atlas/metatlas/blob/master/docs/example_notebooks/data_access_examples%20Methionine%20QExactive.ipynb

**Comment by blink1073** [comment]
It looks to me like the axes are upside down, indeed because of imshow  :smile:

**Comment by blink1073** [comment]
imshow inverts the y axis by default.

**Comment by blink1073** [comment]
Should be fixed by  7996696.

**Comment by blink1073** [comment]
Do you want me to add the `mz_centroid` to part of the default output of `get_heatmap`?

**Comment by benbowen** [comment]
Lets add bells and whistles later. I updated the notebook. Please close
this ticket.

--------------
Email: BPBowen@lbl.gov
Google Voice: (510) 214-6683
Mobile: (480) 225-2341
MS 977-221, Lawrence Berkeley Lab
OpenMSI: http://openmsi.nersc.gov

**Comment by blink1073** [comment]
You know you can close them too right?  :smile;

**Comment by benbowen** [comment]
I didn't know... that's funny.  Where's the button?

--------------
Email: BPBowen@lbl.gov
Google Voice: (510) 214-6683
Mobile: (480) 225-2341
MS 977-221, Lawrence Berkeley Lab
OpenMSI: http://openmsi.nersc.gov

On Fri, Apr 17, 2015 at 10:04 AM, Steven Silvester <notifications@github.com

**Comment by blink1073** [comment]
Gone now, but where the Reopen Issue button is.
