### ISSUE TITLE
The list of compound identifications gets stored as a string

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#60]
The identications are stored as quotes.  This seems unexpected.

atlas = metob.retrieve('Atlas',name='QC Mix Big E-Mac Dataset 20151006')

atlas[0].compound_identifications
Out[15]:
"[u'bdc6d8052090437fba67d97a5e3caef0', u'7a320a1566354ea492b0fede918958b3', u'13945d717fb742a590d0f8d3eadb1654', u'1f3344e141b1488eb09eb22377fc3866', u'a956b9d8f06c46ac8ae535abd2f9c2bb', u'8cd96037e0864199b52697030f7f37b4', u'76cdb18836b047d3a32e6c6a4324c67c', u'52f2c84aa629451da20b8d4bfd4e39b2', u'52d3f67cfeaf4f91b8ab51ac0911302b', u'dfca8293b985445d8b9fe5c066f941a7', u'7d4972d2050c48e1bf4e4561467401cc', u'9e6a04ba8ae14741945a3554698dcf13', u'e0710df8086d4c6d862a32c9b794e614', u'301ffc1c106d42ec86389a6c64b0534f', u'154465fd5b014870ba217ff48f9ae4cf', u'bfeff0a4d8e24cd9b9bbc3aa618140ae', u'14336cc074af46d788eb5edc817f6a74', u'bb715a25ddd84094a708638f060dd606', u'5271395cea494dc4814e16ac62662c86', u'e313dc5145e340bb880bde05d3366c24', u'616f49f757514d9faccfc4f6155ff44b', u'3eee860601114e42868b937d5f90e81b', u'245d97654d504a73925252a17b8c1516', u'2993f3098a0440aa806fca196457eaf7', u'928b1cc1b06e4238a72c75797eb92a9d', u'bd745bf231fd419a9e985eb5dbd1e05c', u'f654e62e46664c2f961ff77ad6e9e958']"

**Comment by blink1073** [comment]
When I run those two lines of code I see a print out of dictionaries, as expected.  Can you try again?

**Comment by benbowen** [comment]
When you do:
atlas = metob.retrieve('Atlas',name='%20151016_KZ_Positive_Hilic_QExactive_AvenaExudates%')
# metob.edit_objects(atlas)
atlas

The correct information is printed, but when you do:
atlas = metob.retrieve('Atlas',name='%20151016_KZ_Positive_Hilic_QExactive_AvenaExudates%')
metob.edit_objects(atlas)
atlas

The atlas gets screwed up.

**Comment by blink1073** [comment]
Fixed in 8b0ab4a.

**Comment by benbowen** [comment]
Why does this not work:
atlas =
metob.retrieve('Atlas',name='%20151016_KZ_Positive_Hilic_QExactive_AvenaExudates%')[0]

but this does:
atlas =
metob.retrieve('Atlas',name='%20151016_KZ_Positive_Hilic_QExactive_AvenaExudates%')
myAtlas = atlas[0]

Maybe this is my python ignorance.

**Comment by blink1073** [comment]
The first one should work, what is the error?



—

**Comment by benbowen** [comment]
No error, it just messes up the identifications:

[image: Inline image 1]

**Comment by blink1073** [comment]
Your image didn't make it.  I tried it and it works for me, maybe you need a kernel restart.

**Comment by benbowen** [comment]
That must have been it.  I can't reproduce it now either.
