### ISSUE TITLE
retention time references can be created but not retrieved/saved

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#61]
I made compound identifications that had "compound" and two "references": an mz and rt reference.

Everything is defined and saved, but when retrieved, the RTmin, RTmax, and RTpeak are all zero.

The code is here:

http://nbviewer.ipython.org/url/portal.nersc.gov/project/openmsi/Spreadsheet_To_Atlas.ipynb?flush_cache=true

**Comment by blink1073** [comment]
Fixed by renaming the fields (they were `Rt` in the table and `RT` in metob).
