### ISSUE TITLE
Broken names in lcmsrun.interact()

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#62]
myRun[0].interact()
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-a08318ce6866> in <module>()
----> 1 myRun[0].interact()

/global/project/projectdirs/metatlas/anaconda/lib/python2.7/site-packages/metatlas/metatlas_objects.pyc in interact(self, min_mz, max_mz, polarity, ms_level)
    813         """
    814         import matplotlib.pyplot as plt
--> 815         from metatlas import get_XIC, get_spectrogram, get_info
    816         fid = tables.open_file(self.hdf5_file)
    817 

ImportError: cannot import name get_XIC

**Comment by blink1073** [comment]
Fixed in 6edc450.
