### ISSUE TITLE
How to get newest only from metob.retrieve()

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#63]
When I ask for a metatlas object, and there are multiple objects with the same name, multiple objects are returned.  

Can you remind me how to only get the newest one?

**Comment by blink1073** [comment]
You should only get the most recent unless you have run `.clone()` or saved someone else's object.  Can you give an example?  (Either way, they should come in order, so `objects[-1]` should be the most recent).

**Comment by benbowen** [comment]
Perfect.  It was because one copy was made by katezh and one by bpb.  [-1]
works!
