### ISSUE TITLE
Figure out a good thing to do when no data is found

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#67]
Currently, whenever no data is found, I handle it in a sloppy way.  Can you recommend a good strategy?  

The h5q commands do this:

/global/project/projectdirs/metatlas/anaconda/lib/python2.7/site-packages/metatlas/h5_query.pyc in get_data(h5file, ms_level, polarity, **kwargs)
    147 
    148     if not data.size:
--> 149         raise ValueError('No data found matching criteria')
    150 
    151     if kwargs.get('verbose', None):

ValueError: No data found matching criteria

**Comment by blink1073** [comment]
I don't follow what you're asking.

**Comment by benbowen** [comment]
Currently, I make my data requests like this:

        return_data['eic'] = {}
        try:
            rt,intensity = h5q.get_chromatogram(fid, 
                                            mz_min, 
                                            mz_max,
                                            ms_level,
                                            polarity)
            return_data['eic']['rt'] = rt
            return_data['eic']['intensity'] = intensity
            return_data['eic']['polarity'] = polarity
    
        except:    
            return_data['eic']['rt'] = []
            return_data['eic']['intensity'] = []
            return_data['eic']['polarity'] = []

My gut tells me there is  a smarter way to handle the no data found issue.

**Comment by blink1073** [comment]
We could have `get_chromatogram` return `None, None` if there is no data.

**Comment by blink1073** [comment]
or `[], []` if you prefer

**Comment by benbowen** [comment]
That would be great.  Whatever you think is best.  Something consistent for get_data, chromatogram, spectra, etc.

**Comment by blink1073** [comment]
Fixed in 4e18552 by returning `[], []`.
