### ISSUE TITLE
Fix pickling of objects with MetList attributes

### ISSUE THREAD

**Issue by blink1073** [metabolite-atlas/metatlas#68]

**Comment by blink1073** [comment]
@benbowen, I think the only solution is to use `dill`, a superior version of `pickle`.  I tried it and it works, and `dill` is now installed on `ipython.nersc.gov`.

**Comment by benbowen** [comment]
dill is working just great.  Thanks!

**Comment by blink1073** [comment]
Great, this type of project is exactly what dill was created for.
