### ISSUE TITLE
Refactor metatlas_objects into separate files

### ISSUE THREAD

**Issue by blink1073** [metabolite-atlas/metatlas#73]

**Comment by mkopala** [comment]
@blink1073: I just noticed this issue.  I see you did a bunch of coding over the weekend.

I was actually thinking last week that it might be nice to have each of the classes in `metatlas_objects.py` in its own file as well.  In fact, that's what I thought this case was about reading the name.

**Comment by blink1073** [comment]
My intent was to separate `MetatlasObject` and its subclasses from the utilties built up around it.  I am generally :-1: on having one class per file.
