### ISSUE TITLE
Migrate cron jobs to corigrid

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#75]
Edison is offline for moving from Oakland to Berkeley.  Lisa says that corigrid is working.  Migrate dirwatch and dirwatch2 to that crontab.
I just did 
ssh cori.nersc.gov
and
ssh corigrid
both worked.

**Comment by blink1073** [comment]
I don't appear to have access to pasteur on corigrid.

**Comment by benbowen** [comment]
It works for me. Can you try again?  A ticket to consult@nersc.gov if you
still can't.

# Login the normal way
ssh cori.nersc.gov

# then ssh to corigrid
ssh corigrid
# re-enter credientials

module load globus
myproxy-logon -s nerscca.nersc.gov
gsissh localhost -p 2222 -l pasteur
whoami

**Comment by blink1073** [comment]
Still doesn't work, ticket submitted.  You can kick off the job as pasteur by running:

```bash
crontab project/projectdirs/metatlas/crontab.edison.pasteur
```

**Comment by blink1073** [comment]
Fixed.

```bash
pasteur@cori17:/project/projectdirs/metatlas> crontab crontab.edison.pasteur
pasteur@cori17:/project/projectdirs/metatlas> crontab -l
# DO NOT EDIT THIS FILE - edit the master and reinstall.
# (crontab.edison.pasteur installed on Fri Dec  4 12:46:49 2015)
# (Cron version V5.0 -- $Id: crontab.c,v 1.12 2004/01/23 18:56:42 vixie Exp $)
*/10 * * * * test `find "/global/project/projectdirs/metatlas/dirwatch2.log" -mmin +5` && /global/project/projectdirs/metatlas/run_dirwatch2.sh >& /global/project/projectdirs/metatlas/dirwatch2.log
*/10 * * * * /global/project/projectdirs/metatlas/run_dirwatch.sh >& /global/project/projectdirs/metatlas/dirwatch.log
