### ISSUE TITLE
Add fields to compounds table

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#76]
We need some extra fields in the compounds table.  I underestimated a bit of complexity.  The following fields are needed in addition to what we currently have:

permanent_charge: signed integer
inchi_key: string
number_components: integer (one or greater)
neutralized_inchi: string (can be 100s of characters)
neutralized_inchi_key: string
neutralized_2d_inchi: string (can be 100s of characters)
neutralized_2d_inchi_key: string

**Comment by blink1073** [comment]
Fixed.  I also renamed `InChI` -> `inchi` and `MonoIsotopic_molecular_weight` -> `mono_isotopic_molecular_weight`.

See http://metabolite-atlas.github.io/metatlas/source/api/metatlas.html#compound.
