### ISSUE TITLE
Update readme notebook link to render in github

### ISSUE THREAD

**Issue by blink1073** [metabolite-atlas/metatlas#80]

**Comment by blink1073** [comment]
Sphinx was not rendering source code blocks from markdown properly, so I'm keeping it in RST.

**Comment by mkopala** [comment]
I'm sure it's clear to you guys, but this case isn't clear to me.  Are you talking about the link in the main README?.  This one:

> See example notebook.

That notebook doesn't exist any more.  I noticed that last week.  I learned last week that GitHub renders `.ipynb` files directly now as well:

* [metatlas/Convert Many Files.ipynb at master · metabolite-atlas/metatlas](https://github.com/metabolite-atlas/metatlas/blob/master/docs/example_notebooks/Convert%20Many%20Files.ipynb)

**Comment by blink1073** [comment]
Yeah, that's what we meant.  The nbviewer site tends to go down periodically, so we'd like to use a github link there.

**Comment by aitatanit** [comment]
Updated link.
