### ISSUE TITLE
Design a strategy to speed up the get data process when looping through large number of files and compounds

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#82]
When looping through files in groups and compounds in an atlas, its common to need ~10K separate requests via h5query.  For example, if there are 200 Lcmsruns and 200 compounds that is 40K mz@rt@file conditions.  Furthermore, the user will likely want MS1 and MS2 slices from the file, chromatogram, and MS1 summary data.

Currently, this scenario requires 1-2 hours to complete using ipython.nersc.gov.  There are several options to accelerate this

1. Parallelize the request.  This could be done using NERSC resources via NEWT.  Also, ask Shreyas what plans he has for parallel processing at NERSC.  We could also use something outside like Amazon or our local clusters for this task.  In principle, MetAtlas has access to an "immediate" queue on Cori, but I haven't tested it yet.
2. Create copies of the data in the hdf5 file that are optimized for m/z slicing.  Currently, they are optimized for time-slicing because data is stored as spectra acquired at discrete times.  We did this in OpenMSI by duplicating, compressing, and chunking data in hdf5.
3. Analyze the 40K requests; using indexing or blocked data requests process the results in a way more efficient than the naive approach currently in use.  Something as simple as a) load an entire hdf5 file into memory using "h5query.get_data"; b) organize the numpy array and delete unneeded values while sorting and indexing desired values; c) slice it and create a return list, would likely give at least one order of magnitude improvement.  Sounds like a homework assignment in an algorithms class.
4. Some combination of 1, 2, and 3.

I like option 3 the most.  When I used to do this kind of thing locally, that is what I would do.  

I also like option 1 using NEWT since this will affect other needs of the project.

@blink1073 @mkopala @aitatanit what do you all think?  

My summary of thoughts is: If everyone agrees that option 3 is the best thing then I can create a ticket for this and a separate ticket for option 1.  Steve and I talked about option 2 from the beginning.  It really makes a research project all of its own, and I would rather delay that until we are fully functional.  Someone can do option 2 as an independent research project and really optimize the file format to a saturation point.

**Comment by mkopala** [comment]
For (2), it looks like #55 already covers that, at least for Chromatograms?

**Comment by blink1073** [comment]
I'd say 2 and 3 should be enough to get what you need.  2 is covered by #55, and 3 would just be a meta method that you pass a bunch of requests to.

**Comment by benbowen** [comment]
3 it is! I'll make a new ticket specific for that.
