### ISSUE TITLE
qgrid not showing decimal points

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#88]
I thought we had an open issue for this, but I can't find it.  My QGrid widgets only show integers.

**Comment by blink1073** [comment]
Which table is giving you trouble?  I just ran this:

<img width="904" alt="screen shot 2015-12-19 at 8 01 47 am" src="https://cloud.githubusercontent.com/assets/2096628/11913356/d69dc864-a626-11e5-89ed-82fb4928bcd7.png">

**Comment by benbowen** [comment]
Its all working for me now.  Who knows.  I tested a few datatypes and they
all work.
