### ISSUE TITLE
Shorten the wait time for cron job

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#94]
If possible, I would like to run the cron job more frequently.  I'm trying to decipher the 10 min with mmin +5, but not sure I understand.  Could we do a */2 with a -mmin +1?  I don't want to mess with this if it will make it more fragile, but if we can shorten the wait it would be more convenient.

These are the current crontab.  The first is our main task; the second is for old metatlas; and the third I don't know what is:

pasteur@cori17:/project/projectdirs/metatlas> cat crontab.edison.pasteur
*/10 * * * * test `find "/global/project/projectdirs/metatlas/dirwatch2.log" -mmin +5` && /global/project/projectdirs/metatlas/run_dirwatch2.sh >& /global/project/projectdirs/metatlas/dirwatch2.log
*/10 * * * * /global/project/projectdirs/metatlas/run_dirwatch.sh >& /global/project/projectdirs/metatlas/dirwatch.log
*/10 * * * * test `find "/global/project/projectdirs/metatlas/dirwatch3.log" -mmin +5` && /global/project/projectdirs/metatlas/run_dirwatch3.sh >& /global/project/projectdirs/metatlas/dirwatch3.log

**Comment by blink1073** [comment]
pasteur@cori17:/project/projectdirs/metatlas> cat crontab.corigrid.pasteur
*/10 * * * * /global/project/projectdirs/metatlas/run_dirwatch2.sh
*/10 * * * * /global/project/projectdirs/metatlas/run_dirwatch.sh >& /global/project/projectdirs/metatlas/dirwatch.log
*/10 * * * * /global/project/projectdirs/metatlas/run_dirwatch3.sh

You can edit that to change just the /10 to whatever you like, then run (as pasteur)
$ crontab -r
$ contab crontab.corigrid.pasteur
