### ISSUE TITLE
qgrid or gui options for pandas dataframe

### ISSUE THREAD

**Issue by benbowen** [metabolite-atlas/metatlas#95]
previously, I could import qgrid and show pandas dataframes.  since the update, I can show lists of metatlas objects, but not dataframes.

**Comment by blink1073** [comment]
The following works:

```
import qgrid
qgrid.nbinstall(overwrite=True)
qgrid.show_grid(my_dataframe, remote_js=True)
```

**Comment by benbowen** [comment]
Works! Thanks!!!
