### ISSUE TITLE
DB Dump

### ISSUE THREAD

**Issue by aitatanit** [metabolite-atlas/metatlas#97]
# Backup DB
- [ ] Backup DB nightly via crontab
- [ ] Copy backup to location not on nersc weekly or monthly

**Comment by benbowen** [comment]
NERSC also has the HPSS tape archive.  Its a very fast connection to copy
data from project to tape on hpss.

**Comment by aitatanit** [comment]
I added instructions to the Admin section on how to clone a DB and move it locally to work with
